package com.berinle;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Sep 10 08:53:10 EDT 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://berinle.com", name = "EmployeeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface EmployeeServicePortType {

    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://berinle.com", className = "com.berinle.AddEmployeeResponse")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://berinle.com", className = "com.berinle.AddEmployee")
    @WebMethod
    public void addEmployee(
        @WebParam(name = "in0", targetNamespace = "http://berinle.com")
        com.berinle.Employee in0
    );
}
