
package com.berinle;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Sep 10 08:53:10 EDT 2010
 * Generated source version: 2.2.9
 * 
 */

public final class EmployeeServicePortType_EmployeeServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://berinle.com", "EmployeeService");

    private EmployeeServicePortType_EmployeeServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = EmployeeService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EmployeeService ss = new EmployeeService(wsdlURL, SERVICE_NAME);
        EmployeeServicePortType port = ss.getEmployeeServiceHttpPort();  
        
        {
        System.out.println("Invoking addEmployee...");
        com.berinle.Employee _addEmployee_in0 = null;
        port.addEmployee(_addEmployee_in0);


        }

        System.exit(0);
    }

}
