
/*
 * 
 */

package com.berinle;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Sep 10 08:53:10 EDT 2010
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "EmployeeService", 
                  wsdlLocation = "http://localhost:8080/sample-xfire/services/employeeService?wsdl",
                  targetNamespace = "http://berinle.com") 
public class EmployeeService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://berinle.com", "EmployeeService");
    public final static QName EmployeeServiceHttpPort = new QName("http://berinle.com", "EmployeeServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/sample-xfire/services/employeeService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/sample-xfire/services/employeeService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public EmployeeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns EmployeeServicePortType
     */
    @WebEndpoint(name = "EmployeeServiceHttpPort")
    public EmployeeServicePortType getEmployeeServiceHttpPort() {
        return super.getPort(EmployeeServiceHttpPort, EmployeeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeServicePortType
     */
    @WebEndpoint(name = "EmployeeServiceHttpPort")
    public EmployeeServicePortType getEmployeeServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(EmployeeServiceHttpPort, EmployeeServicePortType.class, features);
    }

}
